name: test_2
description: "Приложение-агрегатор мастер-классов"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  table_calendar: ^3.0.9  # Для выбора дат

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/