name: test_2
description: "Приложение-агрегатор мастер-классов"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: 4.0.1
  intl: 0.19.0 # Обновленная версия
  table_calendar: ^3.0.9
  go_router: 13.0.1
  provider: 6.1.1
  http: 1.2.1
  shared_preferences: 2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/